# Generated by Django 4.2.4 on 2023-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='users_group',
            field=models.ManyToManyField(related_name='Mailings', to='mailing.customer', verbose_name='группа пользователей для рассылки'),
        ),
    ]
