# Generated by Django 4.2.4 on 2023-09-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_users_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='users_group',
            field=models.ManyToManyField(related_name='Сastomer', to='mailing.customer', verbose_name='группа пользователей для рассылки'),
        ),
    ]
