# Generated by Django 4.2.4 on 2023-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_users_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('day', 'каждый день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='day', max_length=5),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='users_group',
            field=models.ManyToManyField(to='mailing.customer', verbose_name='группа пользователей для рассылки'),
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
    ]
