# Generated by Django 4.2.4 on 2023-09-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailing_periodicity_mailing_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='status_mail',
            field=models.CharField(choices=[('create', 'создана'), ('start', 'запущена'), ('finished', 'завершена')], default='create', max_length=8),
        ),
    ]
