# Generated by Django 4.2.4 on 2023-09-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailing_status_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='attempt',
            field=models.BooleanField(default=False, verbose_name='статус попытки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='дата и время попытки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='massage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.massage', verbose_name='письмо'),
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
    ]
