# Generated by Django 4.2.4 on 2023-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_massage_mailing_mailing_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки'),
        ),
    ]
