# Generated by Django 4.2.4 on 2023-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateField(verbose_name='начало рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateField(verbose_name='конец рассылки'),
        ),
    ]
