# Generated by Django 4.2.4 on 2023-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_start_alter_mailing_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='datetime',
            field=models.DateField(auto_now_add=True, verbose_name='дата и время попытки'),
        ),
    ]
